language: swift
osx_image: xcode9.4
podfile: Example/Podfile

env:
    global:
        - WORKSPACE="Example/DSDMenu.xcworkspace"
        - SCHEME="DSDMenu_Example"
        - SDK="iphonesimulator11.4"
    matrix:
        - DESTINATION="OS=9.3,name=iPhone 6s"
        - DESTINATION="OS=10.3.1,name=iPhone 7"
        - DESTINATION="OS=11.4,name=iPhone 8"

script:
    - set -o pipefail
    - xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty --test --color
    - pod lib lint
