language: swift
osx_image: xcode9.4
podfile: Example/Podfile

env:
    global:
        - WORKSPACE="Example/${POD_NAME}.xcworkspace"
        - SCHEME="${POD_NAME}-Example"
        - SDK=iphonesimulator11.0
    matrix:
        - DESTINATION="OS=9.0,name=iPhone 6s"
        - DESTINATION="OS=10.0,name=iPhone 7"
        - DESTINATION="OS=11.0,name=iPhone 7"

script:
    - set -o pipefail
    - xcodebuild test -enableCodeCoverage YES -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" ONLY_ACTIVE_ARCH=NO | xcpretty
    - pod lib lint